name             'maczero'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures maczero'
long_description 'Installs/Configures maczero'
version          '0.1.0'

depends          'homebrew', '~> 1.9.2'
depends          'dmg'
